CREATE TABLE Photos
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                             NOT NULL,
    description VARCHAR(1000)                            NOT NULL,
    data        BYTEA                                    NOT NULL,
    thumbnail   BYTEA                                    NOT NULL,
    size        VARCHAR(255)                             NOT NULL,
    uploaded_at TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    metadata_id BIGINT,
    CONSTRAINT pk_photos PRIMARY KEY (id)
);

CREATE TABLE Preferences
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    key     VARCHAR(255)                             NOT NULL,
    value   VARCHAR(255)                             NOT NULL,
    user_id INTEGER                                  NOT NULL,
    CONSTRAINT pk_preferences PRIMARY KEY (id)
);

CREATE TABLE Users
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255)                             NOT NULL,
    last_name  VARCHAR(255)                             NOT NULL,
    user_name  VARCHAR(255)                             NOT NULL,
    password   VARCHAR(255)                             NOT NULL,
    user_type  VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE cv
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fileName VARCHAR(255)                            NOT NULL,
    data     OID                                     NOT NULL,
    CONSTRAINT pk_cv PRIMARY KEY (id)
);

CREATE TABLE email
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR(255)                            NOT NULL,
    body  VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_email PRIMARY KEY (id)
);

CREATE TABLE gps_metadata
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    latitude  DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    altitude  DOUBLE PRECISION,
    city      VARCHAR(255),
    country   VARCHAR(255),
    CONSTRAINT pk_gps_metadata PRIMARY KEY (id)
);

CREATE TABLE pdf_files
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uploadedBy  VARCHAR(255)                            NOT NULL,
    fileName    VARCHAR(255)                            NOT NULL,
    data        OID                                     NOT NULL,
    contentType VARCHAR(255),
    labels      TEXT[]                                  NOT NULL,
    size        VARCHAR(255)                            NOT NULL,
    uploadedAt  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    description VARCHAR(255),
    thumbnail   OID                                     NOT NULL,
    CONSTRAINT pk_pdf_files PRIMARY KEY (id)
);

CREATE TABLE photo_metadata
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    image_height    VARCHAR(255),
    image_width     VARCHAR(255),
    camera_make     VARCHAR(255),
    camera_model    VARCHAR(255),
    date_taken      TIMESTAMP WITHOUT TIME ZONE,
    gps_metadata_id BIGINT,
    CONSTRAINT pk_photo_metadata PRIMARY KEY (id)
);

CREATE TABLE weather_cities
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(255)                             NOT NULL,
    country   VARCHAR(255)                             NOT NULL,
    latitude  VARCHAR(255)                             NOT NULL,
    longitude VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_weather_cities PRIMARY KEY (id)
);

CREATE TABLE who_am_i
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    header_title              VARCHAR(255)                            NOT NULL,
    header_into               VARCHAR(255)                            NOT NULL,
    main_content_question     VARCHAR(255)                            NOT NULL,
    main_content_first_title  VARCHAR(255)                            NOT NULL,
    main_content_first_data   TEXT[]                                  NOT NULL,
    main_content_second_title VARCHAR(255)                            NOT NULL,
    main_content_second_data  TEXT[]                                  NOT NULL,
    cv_button                 VARCHAR(255)                            NOT NULL,
    photos                    TEXT[],
    CONSTRAINT pk_who_am_i PRIMARY KEY (id)
);

ALTER TABLE Preferences
    ADD CONSTRAINT uc_7f326cfdbc1d2d30f2f0bd374 UNIQUE (key, user_id);

ALTER TABLE photo_metadata
    ADD CONSTRAINT uc_photo_metadata_gps_metadata UNIQUE (gps_metadata_id);

ALTER TABLE Photos
    ADD CONSTRAINT uc_photos_metadata UNIQUE (metadata_id);

ALTER TABLE Users
    ADD CONSTRAINT uc_users_user_name UNIQUE (user_name);

CREATE INDEX idx_weather_cities_name ON weather_cities (name);

ALTER TABLE Photos
    ADD CONSTRAINT FK_PHOTOS_ON_METADATA FOREIGN KEY (metadata_id) REFERENCES photo_metadata (id);

ALTER TABLE photo_metadata
    ADD CONSTRAINT FK_PHOTO_METADATA_ON_GPS_METADATA FOREIGN KEY (gps_metadata_id) REFERENCES gps_metadata (id);

ALTER TABLE Preferences
    ADD CONSTRAINT FK_PREFERENCES_ON_USER FOREIGN KEY (user_id) REFERENCES Users (id);
